version: '3'

services:
  ocsapplication:
    image: ocsinventory/ocsinventory-docker-image:latest
    container_name : ocsinventory-server
    restart: always
    expose:
      - "80"
    volumes:
      - "./perlcomdata:/etc/ocsinventory-server"
      - "./ocsreportsdata:/usr/share/ocsinventory-reports/ocsreports/extensions"
      - "./varlibdata:/var/lib/ocsinventory-reports"
      - "./httpdconfdata:/etc/apache2/conf-available"
#      - "./install.php:/usr/share/ocsinventory-reports/ocsreports/install.php"
    environment:
      OCS_DB_SERVER: ocsinventory-db
      OCS_DB_USER: ocsuser
      OCS_DB_PASS: ocspass
      OCS_DB_NAME: ocsweb
      # See documentation to set up SSL for MySQL
      OCS_SSL_ENABLED: 0
    links:
      - ocsdb
    networks:
      - localocs
    depends_on:
      - ocsdb
    ports:
      - 8068:80

  ocsdb :
    image : mysql:8.0
    container_name : ocsinventory-db
    restart: always
    expose :
      - "3306"
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./sqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : rootpass
      MYSQL_USER : ocsuser
      MYSQL_PASSWORD : ocspass
      MYSQL_DATABASE : ocsweb
    networks:
      - localocs

networks:
  localocs:


